### ISSUE TITLE
How would I go about making this work with angular?

### ISSUE THREAD

**Issue by MauricioFerraz** [skabbi/eslint-plugin-the-step-down-rule#6]
Hello, I'm interested in using this plugin to order the methods in my components and services in angular, but it only seems to work for functions and arrow functions, and not for the class methods.

Thanks!

**Comment by skabbi** [comment]
> How would I go about making this work with angular?

I basically reverse engineered the [no-use-before-define](https://github.com/eslint/eslint/blob/3ae0574fc78c4a2b406625e4792cb2859cb9bcb1/lib/rules/no-use-before-define.js) rule until I got the behavior I wanted. And that did not include angular use cases. 

I'm not sure if angular has its own version of eslint rules but, if you can give me a few examples of valid and invalid code for testing, I can try to update this package to support it.

**Comment by skabbi** [comment]
Closing because of lack of feedback
