### ISSUE TITLE
[Feature] I would love for this to work for classes

### ISSUE THREAD

**Issue by hrdwdmrbl** [skabbi/eslint-plugin-the-step-down-rule#7]
I assume it would, my mistake. But that is actually my most common situation because most of my code is inside a class

**Comment by skabbi** [comment]
The code and NPM package have successfully been updated to v0.1.0, thanks to @hrdwdmrbl amazing PR [Feat: Work for class methods #8](https://github.com/skabbi/eslint-plugin-the-step-down-rule/pull/8). And can be installed using `npm install eslint-plugin-the-step-down-rule@0.1.0`

@hrdwdmrbl Do you consider the issue to be solved or is there anything else you need?
